### PR TITLE
Feature/2775 input filled hover bg color

### LINKED ISSUE #2: Incorrect Input Focus Color on Mobile Viewports
#### Describe the bug
Incorrect focus color on mobile.

#### What is the expected behavior?
On mobile viewports, input fields should have the same focused color as desktop viewports; they are different right now.  
The mobile input bg focus color is darker.

#### What are the steps to reproduce?
1. Go to React Auth Example
2. Click on Login Field
3. Observe BG Color
4. Make window small
5. Click on Login Field
6. Observe different, darker bg color

#### Screenshots or links to minimum reproduction example
image

#### Environment

Windows, Chrome

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes #2 

#### Changes proposed in this Pull Request:
- Mobile Viewport Focused color fix for Filled Inputs

Before:
Filled Before

After:
Filled After

#### To Test:
- Run the showcase and observe on a mobile device, simulate a phone in chrome dev tools.

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]

**Review by andrupu — APPROVED** [review]
Looks like this one wanted to pull into Master by default.  If we want to make Master the defualt branch, but still PR feature branches to Dev, is there a wa to still auto-pull to dev?  if not, Is there a way to have it not auto-pull to a certain branch at all?.

**Comment by jeffvg** [comment]
> Looks like this one wanted to pull into Master by default. If we want to make Master the defualt branch, but still PR feature branches to Dev, is there a wa to still auto-pull to dev? if not, Is there a way to have it not auto-pull to a certain branch at all?.

looks like it heading to dev?
image

**Comment by andrupu** [comment]
I was referring to how Evan had to change the base branch from Master to Dev.  Apparently, when opening new PRs, GitHub wants to auto-pull everything into the master branch since it has been set as the default branch.

**Comment by joebochill** [comment]
Yes, that is one of the things we will need to be vigilant about now that the default branch is changed...feature PRs should still be going into dev, which will necessitate changing the branch when opening a new PR.

**Pull request merged**
