### PR TITLE
Change pointer to mui v5

### PR DESCRIPTION
**Pull request by huayunh**

### CODE REVIEW

**Comment by joebochill** [comment]
Personally, I would leave the pointer alone. Traditionally, we always have it pointing at the dev branch and update it when things get merged into dev (not for ongoing feature development).

**Comment by huayunh** [comment]
so why is there a "mui-v5" and a "dev"? Why weren't we checking out from `dev` at the beginning?

**Comment by daileytj** [comment]
Even if we update the pointer now, it will need updated everytime a new PR is made in the showcase to keep up with MUI-v5 updates. I would recommend just listing the showcase branch name to checkout in the "how to test" section of PR's. You'll need to do a fresh clone, then `yarn start:showcase` to initialize the submodule and then you can switch branches in the demo/showcase folder to point to the one you want to work with locally.

**Comment by daileytj** [comment]
> so why is there a "mui-v5" and a "dev"? Why weren't we checking out from `dev` at the beginning?

The submodule pointer always points to a specific commit, not a branch. So while it is supposed to point to "dev", it is actually pointing to the last commit on dev

**Comment by joebochill** [comment]
We made a mui-v5 branch because there were multiple parts to the MUI 5 migration (i.e., we couldn't/didn't want to do it all in one PR). And we were making other bug fixes in the dev branch that we wanted to be able to get out without waiting for MUI 5 work to be completed.

**Comment by daileytj** [comment]
Closing this... we can update the pointer once we get everything up to date and pushed to dev

**Pull request closed without merging**
