### PR TITLE
Fix mobile bg

### PR DESCRIPTION
**Pull request by emclaug2**
Fixes # .

#### Changes proposed in this Pull Request:
- Fix hover bg mobile for filled input on mobile devices.

### CODE REVIEW

**Comment by ektasawant** [comment]
Working fine 👍 .

Desktop Hover: `#f1f2f2`
Screenshot 2022-02-02 at 11 36 03 AM

Mobile (hover: none) : `#f1f2f2`
Screenshot 2022-02-02 at 11 35 34 AM

**Comment by emclaug2** [comment]
> Working fine 👍 . Do we have issue link for this?

#2 was merged a couple days ago but it didn't include the code that fixed the bug; there was a commit locally that didn't make it to the original PR.  This is a follow-up PR.  We discovered the missing code whenever I tried to give Joe a demo yesterday.  We ended up coding the fix during the demo instead.

**Comment by ektasawant** [comment]
> We ended up coding the fix during the demo instead.

Thanks for clarification . Working fine 👍 .

**Review by ektasawant — APPROVED** [review]

**Comment by emclaug2** [comment]
@jeffvg this needs a code owner approval; we made these changes during office hours & Joe already had it demo'd so we should be good.

**Pull request merged**
